/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-generic32"
#define DATE "built on: Sun Aug 23 18:36:02 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','u','n',
    'k','n','o','w','n','-','l','i','n','u','x','-','g','n','u','e',
    'a','b','i','h','f','-','g','c','c',' ','-','f','P','I','C',' ',
    '-','p','t','h','r','e','a','d',' ','-','W','a',',','-','-','n',
    'o','e','x','e','c','s','t','a','c','k',' ','-','W','a','l','l',
    ' ','-','O','3',' ','-','m','a','r','c','h','=','a','r','m','v',
    '7','-','a',' ','-','m','f','p','u','=','n','e','o','n','-','v',
    'f','p','v','4',' ','-','m','f','l','o','a','t','-','a','b','i',
    '=','h','a','r','d',' ','-','D','O','P','E','N','S','S','L','_',
    'U','S','E','_','N','O','D','E','L','E','T','E',' ','-','D','O',
    'P','E','N','S','S','L','_','P','I','C',' ','-','D','N','D','E',
    'B','U','G','\0'
};
