/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install"
#define EXEC_PREFIX "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install"
#define BINDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/bin"
#define SBINDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/sbin"
#define LIBEXECDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/libexec"
#define DATAROOTDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share"
#define DATADIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share"
#define SYSCONFDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/etc"
#define SHAREDSTATEDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/com"
#define LOCALSTATEDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/var"
#define RUNSTATEDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/var/run"
#define INCLUDEDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/doc/tar"
#define INFODIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/info"
#define HTMLDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/doc/tar"
#define DVIDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/doc/tar"
#define PDFDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/doc/tar"
#define PSDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/doc/tar"
#define LIBDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/lib"
#define LISPDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/emacs/site-lisp"
#define LOCALEDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/locale"
#define MANDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/man"
#define PKGDATADIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/share/tar"
#define PKGINCLUDEDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/include/tar"
#define PKGLIBDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/lib/tar"
#define PKGLIBEXECDIR "/home/dev/Desktop/ClaraColour/python/crosstoolsng/tar-armhf-install/libexec/tar"
